### ISSUE TITLE
Infernal Robotics Compatibility 

### ISSUE THREAD

**Issue by gomker** [ferram4/Kerbal-Joint-Reinforcement#14] opened 2016-12-22 21:33 UTC
Discussions in the forums has let me to the workaround of setting `multiPartAttachNodeReinforcement = 0` in order to get IR to work correctly. This does allow IR parts to move correctly however, it causes other side effects with larger parts such as [LBP](http://spacedock.info/mod/167/Large%20Boat%20Parts%20Pack) flexing at joints.

Is there a way perhaps to set this option to only affect the ignore list?

**Comment by ferram4** [comment] 2016-12-22 22:11
The ignore list should automatically disable multijoint reinforcement.  That is the purpose of the ignore list.  I'll look to see where things are going wrong.

The global disable for that feature will not be removed, the purpose of it is to help identify the cause of issues.

**Comment by gomker** [comment] 2016-12-22 22:20
Thanks - Let me know if you would like me to provide any more examples or data.

**Comment by ferram4** [comment] 2017-01-26 02:27
I've made some changes that I believe have fixed this.  Please check it with the latest build to be certain that it's working, I don't do anything with IR so I wouldn't know what to specifically test for.

**Comment by gomker** [comment] 2017-01-26 03:30
Looks good so far from my first test, all the issues I was having are corrected.

**Comment by rsparkyc** [comment] 2017-03-27 14:14
I have also done some testing with the latest dev build, and it seems to be working better for me as well.

**Comment by ferram4** [comment] 2017-05-18 20:10
Since it has been reported as fixed and there haven't been any additional reports, I'm closing this.

**Closed by ferram4** 2017-05-18 20:10 UTC
