### ISSUE TITLE
Strange docking port behavior

### ISSUE THREAD

**Issue by vtdmhd** [ferram4/Kerbal-Joint-Reinforcement#4] opened 2015-02-06 07:11 UTC
Tested on stock + KJR: 
 addition of one part to  the craft makes the two crafts become stuck to each other after undocking.

This does not happen in stock game.

Craft files: http://1drv.ms/1DFxbe8

**Comment by ferram4** [comment] 2015-02-07 22:09
Duplicate of #3, and has already been addressed, just pending release.

**Closed by ferram4** 2015-02-07 22:09 UTC
Labels: duplicate
